### ISSUE TITLE
card randomly resets while editing it

### ISSUE THREAD

**Issue by robertboccia** [MelleD/lovelace-expander-card#181] opened 2024-06-25 12:28 UTC
READ THIS FIRST:
Thanks for raising a expander card issue. Please take the time to review the following
categories as some of them do not apply here.

🙅 "Please DO NOT Raise an Issue" Cases
- Question
STOP!! Please ask questions about how to use something, or to understand why something isn't
working as you expect it to Github discussion or on forum https://community.home-assistant.io/t/expander-accordion-collapsible-card/738817/4.
- Managed Dependency Upgrade
You DO NOT need to raise an issue for a managed dependency version upgrade as there's a semi-automatic process for checking managed dependencies for new versions before a release. BUT pull requests for upgrades that are more involved than just a version property change are still most welcome.
- With an Immediate Pull Request
An issue will be closed as a duplicate of the immediate pull request, so you don't have to raise an issue if you plan to create a pull request immediately.

🐞 Bug report (please don't include this emoji/text, just add your details)
Please provide details of the problem, including the version of expander card and your Brwoser that you
are using. If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it
For quick troubleshooting, prepare a [minimally reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example).

!!!Please check your Browser console for Javascript errors!!!

TIP: You can always edit your issue if it isn't formatted correctly.
     See https://guides.github.com/features/mastering-markdown

**Comment by MelleD** [comment] 2024-06-25 19:02
@robertboccia did you read the text? Would like to add some content?

**Comment by robertboccia** [comment] 2024-06-26 08:28
sure, card is constantly resetting as you are editing it, not sure how to explain this better, or if i am the only one experiencing this behavior, happens while editing or adding the card to a dashboard

**Comment by MelleD** [comment] 2024-06-26 09:39
You have to provide some infos like HA, Card version browser etc. or show a video.
Did you delete your cache?
I cannot reproduce it, so hard to say something

**Comment by duczz** [comment] 2024-06-26 10:02
@robertboccia this was a problem in an old version, update or clear cache fix that problem

**Comment by robertboccia** [comment] 2024-06-26 10:12
im on v 1.5.1 and hassos 2024.6.4 which version should i be on?

**Comment by duczz** [comment] 2024-06-26 10:16
In Browser Developer Mode Shows 1.5.1 or in hacs?

**Comment by robertboccia** [comment] 2024-06-26 10:19
hacs, same thing happens in the android app as a test

**Comment by duczz** [comment] 2024-06-26 10:22
And which Version shows in the Browser Developer Mode? F12

**Comment by robertboccia** [comment] 2024-06-26 10:28
all f12 gives me is the console in my edge browser, what version are you talking about?

**Comment by MelleD** [comment] 2024-06-27 17:59
This version in the console:

<img width="671" alt="Bildschirmfoto 2024-06-27 um 19 57 00" src="https://github.com/MelleD/lovelace-expander-card/assets/6340898/e112fa01-f483-4d4d-8889-d5fa92055cb3">

And also maybe a screenshot from your expander card what you are using for components etc.
What are you clicking etc. etc. without information it's not possible to help

**Comment by robertboccia** [comment] 2024-06-28 19:33
Expander card is being loaded as 1.5.1
Using entity card and tile cards

**Comment by duczz** [comment] 2024-06-28 20:10
And the Problem ist still available?
This was normaly fixed in ~1.1.2.

**Comment by MelleD** [comment] 2024-06-28 20:20
> Expander card is being loaded as 1.5.1 Using entity card and tile cards

Not sure what I should say more than  I cannot reproduce it.
You have to deliver more infos or just use the yaml code

**Comment by Caligo82** [comment] 2024-07-04 16:10
I have the same issue. It's not really resetting it in terms of content. But the view of the card gets reset indeed. Have to be fast while editing.

**Comment by Kagey-cmd** [comment] 2024-07-09 18:31
I just installed today with an up-to-date HAss. Experiencing the same problem. My solution was to use the Raw Configuration Editor. When editing the card directly (GUI and YAML), the card would reset completely and all around act very strange, like replacing its entire YAML contents with that of one of the child cards.

**Comment by MelleD** [comment] 2024-07-09 20:43
Iam using only yaml works fine.

Without a whole example or steps to reproduce nothing will happen here on this issue.

**Comment by illuzn** [comment] 2024-07-10 04:53
Not sure if mine is the same as OP but I have reproduction steps for the bug I'm experiencing which is similar in description.

Move to a new issue if this is not the same.

### Bug

Editing a sub-card of the expander card (if _start expanded_ is not on) in the new _sections_ experimental view causes the preview to collapse.

Sections appears to be the way forward (because [as explained the old masonry view results in a much more random ordering  of cards when screen size or card size changes)](https://www.home-assistant.io/blog/2024/03/04/dashboard-chapter-1/).

### Reproduction Steps

1. Minimum HA version 2024.3 (version which introduces sections).
2. Create a view using the new _sections_ experimental layout.
3. Add expander card to a section.
4. Turn off _start expanded_.
5. Add a sub-card (can be any but I used tile).
6. Expand the preview of the card.
7. Change anything regarding the subcard (e.g. toggle show state).

This issue also affects editing the yaml.

### Other diagnostic steps taken.

Have confirmed this issue does not exist in masonry view.

**Comment by MelleD** [comment] 2024-07-14 10:58
Currently in editor mode the expander is open

  ```
      if (isEditorMode) {
            open = true;
        } else {
```

So this could be changed.

**Comment by illuzn** [comment] 2024-07-14 12:10
> Currently in editor mode the expander is open
> 
>   ```
>       if (isEditorMode) {
>             open = true;
>         } else {
> ```
> 
> So this could be changed. 
>          

At least for me this just doesn't work.

**Comment by MelleD** [comment] 2024-07-14 13:04
Ok so should I remove this?

How I said before I don’t use the editor. So someone else have to take over to maintain the new feature from HA or fix bug.

Or like in other component I remove it completely and just support raw yaml

**Comment by robertboccia** [comment] 2024-07-14 13:24
Maybe raw yaml

Robert Boccia
________________________________

**Comment by MelleD** [comment] 2024-07-14 14:16
Yes if nobody uses the editor I can remove it 

@duczz do you use it?

**Comment by duczz** [comment] 2024-07-14 15:36
@MelleD danke der Nachfrage, ich bin mittlerweile flexible, da meine Cards oft yaml only erfordern (card_mod) :)
Hasse es aber trotzdem, weils als noob einfach länger dauert bis es klappt ^^

Wenn ich aus Anfänger Sicht denke, ist GUI immer schöner. Denke die Entscheidung liegt ganz bei dir.
Wobei ich die Probleme iwie nicht nachstellen kann, bei mir klappts immer auch unter sections, würds gerne nachstellen.

**Comment by MelleD** [comment] 2024-07-14 15:47
That comes with practice ;). if you completely use yaml You just need a good IDE like the Visual Studio addon. This works quite well. I have my entire dashboard with yaml only mode. You can do a lot more with it. 

@all
I also tried to recreate it and couldn't get it to work. It is probably due to the components used themselves that there are known problems with this inline yaml editor. It's also funny that no one can come up with a complete example to reproduce the bug. For this reason, I decided not to invest time in the editor. If the requests and bugs pile up I will throw it out or someone else will take over the maintenance. 
But for me there is no benefit just time wasting

**Comment by duczz** [comment] 2024-07-14 15:51
i think i can recreate the issue now when i have understand it right @MelleD (see gif) -  i my eyes a not so critical issue
Edit: on mansory the card still be open when you remove a entity
Edit2: if that was the problem we were talking about in past, we are all talken about different things ^^ - i think the code will be resetted like in a early version
![Animation2](https://github.com/user-attachments/assets/6dbe7fcb-360a-4b88-825a-31949b30e247)

**Comment by MelleD** [comment] 2024-07-14 18:46
@duczz can you send the yaml code of the entities? And what happen if you save after removing a entity? Is this just a preview issue?

If I remove a card with x the expander is NOT closed.

**Comment by illuzn** [comment] 2024-07-15 00:17
@duczz that is the exact issue I'm encountering... it's just a preview bug so not so critical.

@MelleD the issue is not from removing a card but from changing an element in the card (in this case he removed an entity to change an element but for me it also occurs if I change anything e.g. change one of those toggles). By the way, just tested... it also affects using yaml.

It also _only_ occurs on the new _sections_ view for me. So this may be why you are having difficulty reproducing.

**Comment by duczz** [comment] 2024-07-15 15:45
@illuzn okay, than we talked from different things before :)
@MelleD problem is in old and new dashboard (mansory / section) (only preview, yes)

```
type: custom:expander-card
gap: 0.0em
expanded-gap: 0.6em
padding: 1em
clear: false
title: ' test'
overlay-margin: 0.0em
child-padding: 0.0em
child-margin-top: 0.0em
button-background: transparent
expander-card-background: var(--ha-card-background,var(--card-background-color,#fff))
header-color: var(--primary-text-color,#fff)
arrow-color: var(--arrow-color,var(--primary-text-color,#fff))
expander-card-display: block
title-card-clickable: false
min-width-expanded: .nan
max-width-expanded: 0
cards:
  - type: entity
    entity: sensor.cryptoinfo_btc_price_eur
    name: test

```

**Comment by juanpintom** [comment] 2024-08-17 22:44
I've problems too, but idk how to replicate

**Closed as completed** 2024-08-19 09:15 UTC
Labels: wait-for-user-input, wait-for-mre
